### ISSUE TITLE
Ability to customize the toggle query string text

### ISSUE THREAD

**Issue by AdrianoCahete** [stephenkr/nuxt-feature-toggle#11]
First of all: thanks for that plugin!

I'm using to show different versions to my portfolio to different industries.  

But can we have the ability to change the toggle on query string? Today we need to use the `toggle_` string. If we can customize to show something less auto-explanatory (like `_t`, `_tg` or anything different) will be awesome!

**Comment by stephenkr** [comment]
Hi @AdrianoCahete sure this shouldn't be difficult to support, I'll add it.

**Comment by stephenkr** [comment]
Hi @AdrianoCahete, the prefix option has been added in v1.1.0.

https://www.npmjs.com/package/nuxt-feature-toggle
