### ISSUE TITLE
Expose true toggle setting in $featureToggles

### ISSUE THREAD

**Issue by RyanMulready** [stephenkr/nuxt-feature-toggle#14]
Say I wanted to handle the feature toggle inside a vue hook.

```javascript
nuxt.config.js
toggles: {
  'my-toggle': true,
}



component.vue
mounted() {
  if($this.$featureToggles['my-toggle']) {
    alert('my-toggle is on!');
  }
}
```

This works well.  Except if I want to over ride it by using `queryString: true` ie: `/?my-toggle=false`.  The way the library is injecting `$featureToggles` into nuxt [here](https://github.com/stephenkr/nuxt-feature-toggle/blob/master/lib/plugin.js#L16) but evaluating the query string in the component means this is not possible.

For now the work around is to check the query string yourself but it would be nice if the module had this functionality built in.

**Comment by stephenkr** [comment]
Hi @RyanMulready sorry i'm only replying now.

Yes, good idea. Would you be open to contributing a PR :) If not I can work on adding this functionality.

Also thank you for using the module.

**Comment by RyanMulready** [comment]
It's on my backlog!  (Un)fortunately the work around was pretty easy and my backlog is probably as long as yours.  If some free time does pop up I'd be happy to revisit this but can't commit to it for now.

**Comment by stephenkr** [comment]
That's grand, thanks @RyanMulready.

I'll leave this issue open if anyone is interested in implementing it, or I may sometime in the future :)

**Comment by stephenkr** [comment]
Hi, @RyanMulready I think we can now close this issue. Thank you to @israelroldan for adding support 🎉

**Comment by stephenkr** [comment]
New version ready https://www.npmjs.com/package/nuxt-feature-toggle

Thank you again for contributing 🚀
