### ISSUE TITLE
Enhancement: Support runtimeConfig

### ISSUE THREAD

**Issue by superbiche** [stephenkr/nuxt-feature-toggle#20]
Hey there !

Now that Nuxt supports runtimeConfig it would be nice if this module was able to use it, so for the same build we could deploy different features on different environments.  

If you also think it's a good idea I'd be happy to work on a PR for this.  

And thanks for the module. Pretty simple but very useful :+1:

**Comment by stephenkr** [comment]
Hi @superbiche yep this sounds great, feel free to open a pull request.

Also great to hear you're finding it useful :)

**Comment by superbiche** [comment]
Hi @stephenkr 
Actually I made the PR a few days ago but forgot to link it here.  

https://github.com/stephenkr/nuxt-feature-toggle/pull/21

Let me know what you think. I'm using a forked version with these changes merged, in production, it works like a charm :)

**Comment by stephenkr** [comment]
Thank you @superbiche for the contribution, it looks great, I think we can close this issue.
